### ISSUE TITLE
你好，能把emacs配置文件发我一份么？

### ISSUE THREAD

**Issue by liuluheng** [shishougang/wiki#2]
我平时一直都用vim，对emacs不熟，今天下午搞了一下午也没用orgmode成功生成html文件。我看了notes-init.el文件里的两篇文章，照着第二篇里的做了做，但是总报`org-publish-cache-get' called ,but no cache present.不知道是什么意思。我也上网查了些别的资料，但是还是不能解决，所以我想你能把emacs的配置文件发我邮箱一份吗？包括.emacs和.emacs.d里边的内容，非常感谢。我的邮箱是872287087@qq.com.谢谢。

**Comment by shishougang** [comment]
这个https://github.com/shishougang/emacs24-starter-kit 是我的emacs配置的repository。
